"""migracion tabla categorias y productos

Revision ID: 260ba7c5851b
Revises: 
Create Date: 2022-12-29 12:42:01.246839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260ba7c5851b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=45), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unidad', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=45), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('entregas', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=12), nullable=False),
    sa.Column('categorias_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorias_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
